### ISSUE TITLE
PSET

### ISSUE THREAD

**Issue by tiero** [ElementsProject/rust-elements#40]
There are any plans to support PSET format for elements? Thanks

**Comment by apoelstra** [comment]
Yes. But not until Elements Core is up to date with Bitcoin Core 0.21 (see https://github.com/ElementsProject/elements/pull/935) and not until https://github.com/ElementsProject/elements/pull/900 is merged.

**Comment by sanket1729** [comment]
This can now be closed. Pset is supported as of version 0.17

**Comment by tiero** [comment]
Nice! So it is official, Habemus PSET? :heart_eyes:

**Comment by sanket1729** [comment]
We can wait for https://github.com/ElementsProject/elements/pull/900 to be merged, but the spec is _mostly_ finalized and you can build on top 0.17

**Comment by tiero** [comment]
We were waiting for another language to be implemented, so we can start with `go-elements` and `liquidjs-lib` support and start deprecating old (buggish) custom pset support

**Comment by apoelstra** [comment]
I think we're good to close this (in this repo). 900 in Elements is very close.

**Comment by tiero** [comment]
Will this implementation be complete? ie. will include all the roles, blinder, updater etc..?

At the moment, is it right that the only feature complete impl is `elements`? Can be taken as reference for implementing it in other languages?

**Comment by apoelstra** [comment]
> Will this implementation be complete? ie. will include all the roles, blinder, updater etc..?

I don't have a timeline for this. Right now we're focused on [elements-miniscript](https://github.com/ElementsProject/elements-miniscript) which will implement (at least) the Finalizer role, analogously to the split between rust-bitcoin and rust-miniscript. Because PSET is based on PSBT2, which is moving very slowly in Bitcoin-land, we're missing a lot of supporting code that we'd normally be able to merge in from rust-bitcoin.

> At the moment, is it right that the only feature complete impl is elements? Can be taken as reference for implementing it in other languages?

Yes, and yes.
